### ISSUE TITLE
Release SpotBugs 3.1.0

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#111]
Finally SpotBugs is ready to be released. However this might be unstable because we changed build process drastically and this is the first release from new community without enough automated test.

So it would be better to release `release candidate` version first, to ask major users to have a try. This is my opinion, could you tell me yours?

## TODO

* [x] Ask Sonatype to let us deploy artifacts to Maven central
* [x] Update `build.gradle` to enable `uploadArchives` goal
* [x] Prepare changelog for `3.1.0` (#117)
* [x] create and check instructions to use spotbugs with existing maven and gradle plugins
  * see #8 and #15 
  * Updated instructions must be made available on the website's [corresponding section](https://spotbugs.github.io/#using-spotbugs).
* [x] Close [all issues which belongs to 3.1.0 milestone](https://github.com/spotbugs/spotbugs/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22SpotBugs+3.1.0%22)
* [x] Release `3.1.0-rc4` to Maven central
* [x] Release `3.1.0-rc4` to Eclipse plugin update site
* [x] Announce `3.1.0-rc4` release to `findbugs-discuss@cs.umd.edu`
* [x] Test released RC version with several users
  * [x] [fb-contrib](https://github.com/mebigfatguy/fb-contrib)
  * [x] [find-sec-bugs](https://github.com/find-sec-bugs/find-sec-bugs/)
  * [x] [findbugs-slf4j](https://github.com/KengoTODA/findbugs-slf4j)
  * [x] [Findbugs Gradle plugin](https://docs.gradle.org/current/userguide/findbugs_plugin.html)
  * [x] [Findbugs Maven plugin](com.github.hazendaz.spotbugs:spotbugs-maven-plugin , see #8 )
  * [x] Test update of FindBugs plugin installed on Eclipse Neon to SpotBugs plugin (see #209 )
  * [x] Test installation of SpotBugs plugin into Eclipse Oxygen via https://spotbugs.github.io/eclipse-candidate/ update site
  * [x] Test command line scripts execution
  * [x] TBU
* [x] Release more release candidate versions if necessary
* [x] Release `3.1.0` to Maven central
* [x] Release `3.1.0` to Eclipse plugin update site

**Comment by jsotuyod** [comment]
+1 to release a RC first.

I'd add to the checklist, we should create and check instructions to use spotbugs with existing maven and gradle plugins, see #8 and #15. Updated instructions must be made available on the website's [corresponding section](https://spotbugs.github.io/#using-spotbugs).

We can probably do that first with the current snapshot, once we know for sure, make RC1 release, and make the announcement with full instructions to help people check it out.

We should also make sure to have a proper changelog for people comming from Findbugs 3.0.1. We did fix several issues affecting that version...

**Comment by KengoTODA** [comment]
I've updated checklist. Please check.

I'll check how to use findbugs-maven-plugin with spotbugs. It might be hard because Maven doesn't let us exclude direct dependency of plugin.

FYI: I found [changelog generator](https://skywinder.github.io/github-changelog-generator/) which may help us to generate CHANGELOG. But for 3.1.0 release, we should make it by hands because a part of changes aren't managed by issues nor PR in this repository (findbugs repository has related information I guess).

**Comment by KengoTODA** [comment]
I'm working on making changelog, you can check it at https://github.com/spotbugs/spotbugs/compare/master...KengoTODA:changelog

**Comment by KengoTODA** [comment]
Let's release RC1 after we merge #112.

**Comment by KengoTODA** [comment]
3.1.0-RC1 is now on Maven Central.

http://search.maven.org/#artifactdetails%7Ccom.github.spotbugs%7Cspotbugs%7C3.1.0-RC1%7C

**Comment by iloveeclipse** [comment]
Question: what is about Eclipse plugin id, exported packages, contributions and extension point id's. All this still uses old "findbugs" related strings. Changing this is a bigger task, will break (probably) existing clients, not changing this will conflict with "old" findbugs plugin (in the sense that Eclipse used the old "findbugs" plugin will update to the spotbugs once the spotbugs update side will be publicly available and known to the Eclipse). 

Do we have a plan here? I'm not saying we need this for 3.1.0 release, but for later may be?

Another point: I'm the "owner" of the marketplace entry for findbugs (https://marketplace.eclipse.org/content/findbugs-eclipse-plugin). So far I've always updated the entry once we did a findbugs release. Since I feel no reason to support findbugs development anymore, should I change the entry to be "spotbugs" plugin and point to the new home? Or should we create a new entry? WDYT?

**Comment by KengoTODA** [comment]
> Changing this is a bigger task, will break (probably) existing clients, not changing this will conflict with "old" findbugs plugin

Currently we don't change this, so we can replace (upgrade) findbugs plugin with spotbugs plugin as you said.

But it might be better to recommend users to uninstall &amp; install, because upgrading cannot change the tooltip text of icon to switch perspective at least. We may have another unknown problem. I personally prefer to change Eclipse plugin ID.

**Comment by KengoTODA** [comment]
> should I change the entry to be "spotbugs" plugin and point to the new home? Or should we create a new entry? 

I personally think that we need to create a new entry,
Because I also think that [SpotBugs is a last resort to continue FindBugs in Bill's absence](https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004337.html). It's not something to replace FindBugs. Then it's nice to keep entry for FindBugs to welcome Bill's comeback.

It's just my personal opinion, let's keep discussion!

**Comment by h3xstream** [comment]
## Windows script observation

 When using the Windows script [`spotbugs.bat`](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/scripts/windows/spotbugs.bat#L228), it launch the execution in another windows (ui). This can be annoying when using the CLI options.

I don't think this is useful unless special options would be use

```
> start /?
Starts a separate window to run a specified program or command.

START ["title"] [/D path] [/I] [/MIN] [/MAX] [/SEPARATE | /SHARED]
      [/LOW | /NORMAL | /HIGH | /REALTIME | /ABOVENORMAL | /BELOWNORMAL]
      [/NODE <NUMA node>] [/AFFINITY <hex affinity mask>] [/WAIT] [/B]
      [command/program] [parameters]

    "title"     Title to display in window title bar.
    path        Starting directory.
    B           Start application without creating a new window. The
                application has ^C handling ignored. Unless the application
                enables ^C processing, ^Break is the only way to interrupt
                the application.
    I           The new environment will be the original environment passed
                to the cmd.exe and not the current environment.
    MIN         Start window minimized.
    MAX         Start window maximized.
    SEPARATE    Start 16-bit Windows program in separate memory space.
    SHARED      Start 16-bit Windows program in shared memory space.
    LOW         Start application in the IDLE priority class.
    NORMAL      Start application in the NORMAL priority class.
    HIGH        Start application in the HIGH priority class.
    REALTIME    Start application in the REALTIME priority class.
    ABOVENORMAL Start application in the ABOVENORMAL priority class.
    BELOWNORMAL Start application in the BELOWNORMAL priority class.
    NODE        Specifies the preferred Non-Uniform Memory Architecture (NUMA)
                node as a decimal integer.
    AFFINITY    Specifies the processor affinity mask as a hexadecimal number.
                The process is restricted to running on these processors.

                The affinity mask is interpreted differently when /AFFINITY and
                /NODE are combined.  Specify the affinity mask as if the NUMA
                node's processor mask is right shifted to begin at bit zero.
                The process is restricted to running on those processors in
                common between the specified affinity mask and the NUMA node.
                If no processors are in common, the process is restricted to
                running on the specified NUMA node.
    WAIT        Start application and wait for it to terminate.
    command/program
                If it is an internal cmd command or a batch file then
                the command processor is run with the /K switch to cmd.exe.
                This means that the window will remain after the command
                has been run.

                If it is not an internal cmd command or batch file then
                it is a program and will run as either a windowed application
                or a console application.

    parameters  These are the parameters passed to the command/program.
```

**Comment by h3xstream** [comment]
I'm done with the test.
 - [x] I tested SpotBugs on various version of the Spring Framework and its components. (Smoke test)
 - [x] I tested SpotBugs with FindSecurityBugs 1.6.0
 - [x] I ran SpotBugs + FSB on Groovy, Scala, JSP and regular Java bytecode.

**Comment by KengoTODA** [comment]
@iloveeclipse I've tried to replace Eclipse Plugin ID, but I failed (built plugin cannot be installed to Eclipse). Here is [my change](https://github.com/KengoTODA/spotbugs/commit/d5f9854c9bebd3839c9f864734ed6ea6b5dfc033), could you check to find out what I missed?

**Comment by iloveeclipse** [comment]
Now you have the right manifest, how exactly do you install and which error do you have?

**Comment by KengoTODA** [comment]
I have following error, but it seems that I need to use Eclipse 3.6.2 instead of 4.4.0. I will retry to build with that.

## Built with Eclipse Luna (4.4.0) on OSX 10.11.6

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.github.spotbugs.plugin.eclipse,3.1.0.20170417-1492435293335
No repository found containing: org.eclipse.update.feature,com.github.spotbugs.plugin.eclipse,3.1.0.20170417-1492435293335
```

**Comment by KengoTODA** [comment]
Helios also has similar problem:

## Built with Eclipse Helios (3.6.2) on OSX 10.11.6

```
An error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: osgi.bundle,com.github.spotbugs.plugin.eclipse,3.1.0.20170417-1492436124229.
file:/Users/kengo/Documents/github/spotbugs/eclipsePlugin/build/site/eclipse-candidate/plugins/com.github.spotbugs.plugin.eclipse_3.1.0.20170417-1492436124229.jar
Artifact not found: org.eclipse.update.feature,com.github.spotbugs.plugin.eclipse,3.1.0.20170417-1492436124229.
file:/Users/kengo/Documents/github/spotbugs/eclipsePlugin/build/site/eclipse-candidate/features/com.github.spotbugs.plugin.eclipse_3.1.0.20170417-1492436124229.jar
```

**Comment by iloveeclipse** [comment]
Kendo, I have no time to setup the environment, can you please share the build artifacts (update site zip) you generate out of the build? I don't think the problem is Eclipse version related, I guess something is broken after all restructure work. BTW, was you able to install the plugin *before* changing plugin name?

**Comment by KengoTODA** [comment]
> was you able to install the plugin before changing plugin name?

Yes I could.

I will share the built plugin by email, please check the email from 3184815625@qq.com. Thanks for your help!

**Comment by iloveeclipse** [comment]
eclipse-candidate\plugins directory in the zip file contains edu.umd.cs.findbugs.plugin.eclipse_3.1.0.20170417-1492436124229.jar.

The jar name must be com.github.spotbugs.plugin.eclipse_3.1.0.20170417-1492436124229.jar.

Additionaly, I'm not sure if the content of the artifacts.xml is properly generated: it contains such parts like below, where I suspect some variables are still unresolved:

`  <mappings size='3'>
    <rule filter='(&amp; (classifier=osgi.bundle))' output='${repoUrl}/plugins/${id}_${version}.jar'/>
    <rule filter='(&amp; (classifier=binary))' output='${repoUrl}/binary/${id}_${version}'/>
    <rule filter='(&amp; (classifier=org.eclipse.update.feature))' output='${repoUrl}/features/${id}_${version}.jar'/>
  </mappings>`

**Comment by KengoTODA** [comment]
Thanks, I've updated `build.gradle` and finally I could install the built plugin.
But its behaviour is not same with previous (it cannot list bugs in Bug Explorer), I'll continue investigation.

Here is current update: https://github.com/spotbugs/spotbugs/compare/master...KengoTODA:fa7ebd6

**Comment by iloveeclipse** [comment]
@KengoTODA, I've created issue #155 to work on. See https://github.com/iloveeclipse/spotbugs/commit/720edcb2e32488edbc89fced07f806fbe500e6c7. This should fix eclipse issues you've observed. I'm still fighting with gradle build, so not sure if this works or not, but at least in half-broken debugger it looks OK now.

**Comment by KengoTODA** [comment]
Great, I will check. I may merge more changes including https://github.com/KengoTODA/spotbugs/commit/4ba3cf97c27a21ce1ae36e2f4268f1b08b510249 and https://github.com/KengoTODA/spotbugs/commit/fa7ebd64e11ad2b5374a2e0b6dcf5888b94957f9.

**Comment by KengoTODA** [comment]
I confirmed that your branch https://github.com/iloveeclipse/spotbugs/commits/change-eclipse-plugin-id works as expected! Could you propose a PR?

**Comment by KengoTODA** [comment]
I also made a content for SpotBugs Eclipse Plugin in Eclipse Marketplace:
https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin

But its update site URL returns 404 for now.

**Comment by iloveeclipse** [comment]
Just created pr #157.

**Comment by KengoTODA** [comment]
In my understanding, we still have one blocker to release `3.1.0`:

* Incorrect version in Eclipse Update site (#173)

#89, #130 and #162 are also better to fix/discuss.

I expect that #147 has been solevd by changing Eclispe Plugin ID, but not confirmed by author of that issue (because we haven't publish Eclipse Plugin yet).

**Comment by KengoTODA** [comment]
To ensure that Eclipse update site works, I will release RC3 later.

**Comment by iloveeclipse** [comment]
I think we are pretty close to a RC4: https://github.com/spotbugs/spotbugs/milestone/1
we need:
 - fix Eclipse plugin to offer itself as an update to old one #209 , @sewe is working on that
 - decide on #6 and #228 if they need to be done before release
 - finalize Maven support #8 

and after that:
 - build RC 4 to pick latest fixes
 - rebuild and push the most recent docs version

**Comment by bhollis** [comment]
Don't forget to build a new version of the gradle plugin - right now, missing 528410a8d881c9900bf17d6cbb402d119168a06f means we can't test out the RC* versions from Gradle.

**Comment by iloveeclipse** [comment]
> right now, missing 528410a means we can't test out the RC* versions from Gradle.

528410a is merged now. 

What else is needed to build Gradle plugin, or let say it differently: who did this before and do we need to upload something to some repo somewhere in the Gradle/maven universe?

**Comment by bhollis** [comment]
The plugin is at https://plugins.gradle.org/plugin/com.github.spotbugs, but I'm not sure who built/published the last version on June 10th.

**Comment by KengoTODA** [comment]
If nobody handles releasing RC4, I will handle it but I wish before release we fix javadoc and changelog at least regarding https://github.com/spotbugs/spotbugs/pull/269#issuecomment-316536952

**Comment by KengoTODA** [comment]
BTW all the release procedures are listed in https://github.com/spotbugs/spotbugs/blob/master/RELEASE_PROCEDURE.md

About auto release (e.g. ask Travis CI to release if tagged commit was pushed to `master`), it's possible and we can find many helpful entries:

* https://docs.travis-ci.com/user/encrypting-files/
* https://github.com/making/travis-ci-maven-deploy-skelton
* https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/

I also want to automate uploading zip and tarball to GitHub releases, and it should be supported by https://docs.travis-ci.com/user/deployment/releases/

**Comment by iloveeclipse** [comment]
I wish #268 to be fixed before RC4 too.

**Comment by iloveeclipse** [comment]
**@ all**: I think we should create RC5. The major changes:
 - We ship ASM 6 beta
 - We changed the maven plugin to be part of the project, I'm not sure if there is something else to work on (see #8).
- Gradle plugin issue #291 seem to be fixed
- We auto-deploy Eclipse plugin builds on every merged commit

So looking on https://github.com/spotbugs/spotbugs/milestone/1, we are done.

WDYT?

**Comment by KengoTODA** [comment]
+1 to release RC5. I prefer merging #313 before release, then we can confirm that the deployment to eclipse-candidate site works as expected.

**Comment by KengoTODA** [comment]
#313 has been merged. If we have no other request, I will release RC5.

**Comment by KengoTODA** [comment]
I will release RC6 after #337 is merged, please let me know if you have more changes to introduce.

**Comment by KengoTODA** [comment]
Let's wait bcel 6.1 release to close #89 before RC6

**Comment by RAKESHNM** [comment]
@KengoTODA 
Does MyEclipse 10 supports spotbugs plugin ?

**Comment by KengoTODA** [comment]
@RAKESHNM Not sure. What SpotBugs Eclipse Plugin officially supports is Neon and Oxygen. If MyEclipse 10 is based on them, it probably works.

**Comment by iloveeclipse** [comment]
And let's wait for ASM 6 final (see #373) before the final release.

**Comment by iloveeclipse** [comment]
Guys,I've set the deadline for the release to 15 October, see https://github.com/spotbugs/spotbugs/milestone/1.

The only one planned and open item left is maven plugin, see #8. As soon as this one is closed, we schould create the last RC and enter the "quiet" week with no changes except blocker issues or documentation changes. Ideally after this week we would just flip the version and release 3.1.0. 

Any objections? I'm too fast?

**Comment by iloveeclipse** [comment]
Guys, please check #446. If this is OK, we have RC7 and hopefully next commit will be for 3.1.0 final.

**Comment by iloveeclipse** [comment]
Guys, I need your help!

We were **very** close to release 3.1.0 final, but then I saw that we had two show stoppers:
 - we produce errors while parsing module-info.class files (see #408), but we want support Java 9 where this is one of the basics.
 - we produced "wrong" versions for "final release" Eclipse plugins (see #472)

I have PR's for both issues - #474 and #473.

- The module-info PR #474 should be safe because it basically doesn't let SpotBugs to look inside module-info.class at all by default. No one in the world needs this yet.
- The Eclipse version PR #473 should be safe because it only affects the Eclipse plugin version string generation.

I personally think both PR's are OK to merge for 3.1.0 final **without** an extra RC release, and I really want to have the release coming ASAP.

So here is the question: can we merge both PR's and release 3.1.0 without an extra RC build and another delay, or should we create another RC for testing them?

Do you see any other show stoppers?
Should we wait longer before release?

WDYT?

**Comment by henrik242** [comment]
Merge them and release :)

**Comment by iloveeclipse** [comment]
OK, looks like we've managed to merge everything!

The 3.1.0 release is tagged ( 11c9895) , and I think @KengoTODA will create the github release tomorrow, because it is the date we wrote in release notes :o) . Is that right, Kengo?

@hazendaz, @KengoTODA : as usually I'm unsure about maven stuff. If I recall it right, it will be automatically deployed on the tag, but it would be nice if you could confirm it is there. 

Eclipse stable update site contains already 3.1.0 plugin.

As discussed earlier, we plan to have two branches - one for 3.1.x maintenance and master will be for 4.0.0. Please consider this while fixing bugs.

There is now a wiki for the project and Kengo started already the roadmap for 4.0.0 - feel free to add your items - https://github.com/spotbugs/spotbugs/wiki/Roadmap.

With all this, I guess we have a first release!

**Comment by wrprice** [comment]
3.1.0 available on [Maven Central](http://search.maven.org/#artifactdetails%7Ccom.github.spotbugs%7Cspotbugs%7C3.1.0%7Cjar)

**Comment by KengoTODA** [comment]
> it is the date we wrote in release notes :o
Sorry it was almost 25th at far east :)

I've updated release page, please check. https://github.com/spotbugs/spotbugs/releases/tag/3.1.0

**Comment by iloveeclipse** [comment]
Thanks Kengo. I think we can close this task now.
