### ISSUE TITLE
Make SpecialKind handling thread-safe

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs#28]
Legacy way to handle `SpecialKind` in `OpcodeStack.Item` is not thread-safe. Delete these deprecated API and make new one (added by #27) thread-safe.

## TODO

- [ ] delete `OpcodeStack.Item#specialKindNames` static field, which is public and non-thread safe
- [ ] delete `OpcodeStack.Item#defineNewSpecialKind(String)` static method, which returns wrong value
- [ ] add a `ConcurrentMap` private static field to `OpcodeStack.Item`
- [ ] use new static field in  `OpcodeStack.Item#defineSpecialKind(String)` and  `OpcodeStack.Item#getSpecialKindName(int)` to improve thread safety

refs: #23, #27
